- name: create jetstream user
  become: true
  ansible.builtin.user:
    name: jetstream
    shell: /bin/bash
    create_home: yes

- name: install deps
  become: true
  ansible.builtin.apt:
    name:
      - make
      - golang

- name: get repo
  become: true
  become_user: jetstream
  ansible.builtin.git:
    repo: 'https://github.com/bluesky-social/jetstream.git'
    dest: /home/jetstream/jetstream
    version: main
  register: repo

- name: build jetstream
  become: true
  become_user: jetstream
  ansible.builtin.command:
    cmd: /usr/bin/make build
    chdir: /home/jetstream/jetstream
  when: repo.changed or force_build is defined

- name: copy systemd service file
  ansible.builtin.template:
    src: templates/jetstream.service.j2
    dest: /etc/systemd/system/jetstream.service
  register: service

- name: enable and start jetstream
  ansible.builtin.systemd_service:
    name: jetstream
    daemon_reload: "{{ service.changed }}"
    state: "{% if repo.changed or service.changed %}re{% endif %}started"
    enabled: true

