- name: create ref mirror user
  ansible.builtin.user:
    name: mirror
    shell: /bin/bash
    create_home: yes

- name: create allegedly user
  ansible.builtin.user:
    name: allegedly
    shell: /bin/bash
    create_home: yes

- name: system dependencies
  ansible.builtin.apt:
    name:
      - build-essential # for CGO
      - pkg-config # for rust ssl
      - libssl-dev
      - libclang-dev

- name: ensure db directory
  ansible.builtin.file:
    path: "/mnt/{{ mnt_name }}/data"
    state: directory
    owner: mirror
    group: mirror
    mode: '0700'

#---- golang for ref mirror ----#
- name: get go-ing
  become: true
  become_user: mirror
  ansible.builtin.shell:
    chdir: /home/mirror/
    cmd: |
      set -e
      curl -LO https://go.dev/dl/go1.26.0.linux-amd64.tar.gz
      tar -xzf go1.26.0.linux-amd64.tar.gz
    creates: /home/mirror/go/bin/go

- name: get go-didplc repo
  become: true
  become_user: mirror
  ansible.builtin.git:
    repo: 'https://github.com/did-method-plc/go-didplc.git'
    dest: /home/mirror/go-didplc
  register: mirror_repo

- name: build plc-replica binary (takes a sec!)
  become: true
  become_user: mirror
  ansible.builtin.shell:
    cmd: CGO_ENABLED=1 /home/mirror/go/bin/go build -o /home/mirror/plc-replica -buildvcs=false ./cmd/plc-replica
    chdir: /home/mirror/go-didplc
  when: mirror_repo.changed or force_build is defined

#---- rust for allegedly ----#
- name: get rustup
  become: true
  become_user: allegedly
  ansible.builtin.shell:
    chdir: /home/allegedly
    cmd: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain stable
  args:
    creates: "/home/allegedly/.cargo/bin/rustup"

- name: get allegedly repo
  become: true
  become_user: allegedly
  ansible.builtin.git:
    repo: 'https://tangled.org/microcosm.blue/Allegedly'
    dest: /home/allegedly/allegedly
  register: allegedly_repo

- name: build allegedly (takes a min!)
  become: true
  become_user: allegedly
  ansible.builtin.command:
    cmd: /home/allegedly/.cargo/bin/cargo build --release --bin allegedly
    chdir: /home/allegedly/allegedly/
  when: allegedly_repo.changed or force_build is defined

#---- set up services for both ----#
- name: copy plc-replica systemd service file
  ansible.builtin.template:
    src: templates/plc-replica.service.j2
    dest: /etc/systemd/system/plc-replica.service
  register: mirror_service

- name: enable plc-replica
  ansible.builtin.systemd_service:
    name: plc-replica
    daemon_reload: "{{ mirror_service.changed }}"
    enabled: true

- name: start plc-replica if requested
  ansible.builtin.systemd_service:
    name: plc-replica
    state: "{% if mirror_repo.changed or mirror_service.changed %}re{% endif %}started"
  when: start is defined

- name: copy allegedly systemd service file
  ansible.builtin.template:
    src: templates/allegedly.service.j2
    dest: /etc/systemd/system/allegedly.service
  register: allegedly_service

- name: enable allegedly
  ansible.builtin.systemd_service:
    name: allegedly
    daemon_reload: "{{ allegedly_service.changed }}"
    enabled: true

- name: start allegedly if requested
  ansible.builtin.systemd_service:
    name: allegedly
    state: "{% if allegedly_repo.changed or allegedly_service.changed %}re{% endif %}started"
  when: start is defined
