- name: install os deps
  become: true
  ansible.builtin.apt:
    name:
      - git
      - cmake

- name: install rust by rustup
  shell: curl https://sh.rustup.rs -sSf | sh -s -- -y

- name: get repo
  ansible.builtin.git:
    repo: 'https://github.com/at-microcosm/links.git'
    dest: /home/{{ user }}/links
    version: main
  register: repo

- name: build spacedust (slow!)
  ansible.builtin.command:
    cmd: /home/{{ user }}/.cargo/bin/cargo build --release
    chdir: /home/{{ user }}/links/spacedust
  when: repo.changed or force_build is defined

- name: copy systemd service file
  become: true
  ansible.builtin.template:
    src: templates/spacedust.service.j2
    dest: /etc/systemd/system/spacedust.service
  register: service

- name: enable spacedust
  become: true
  ansible.builtin.systemd_service:
    name: spacedust
    daemon_reload: "{{ service.changed }}"
    enabled: true

- name: start spacedust if requested
  become: true
  ansible.builtin.systemd_service:
    name: spacedust
    state: "{% if repo.changed or service.changed %}re{% endif %}started"
  when: start is defined
