- name: install os deps
  become: true
  ansible.builtin.apt:
    name:
      - git
      - snapper

- name: install rust by rustup
  shell: curl https://sh.rustup.rs -sSf | sh -s -- -y

- name: get repo
  ansible.builtin.git:
    repo: 'https://github.com/at-microcosm/links.git'
    dest: /home/{{ user }}/links
    version: main
  register: repo

- name: build ufos (slow!)
  ansible.builtin.command:
    cmd: /home/{{ user }}/.cargo/bin/cargo build --release
    chdir: /home/{{ user }}/links/ufos
  when: repo.changed or force_build is defined

- name: restore data from backup if requested
  ansible.builtin.command:
    cmd: rsync -ahP "/home/{{ user }}/backup/ufos/" /mnt/data/
  when: restore_backup is defined

- name: copy systemd service file
  become: true
  ansible.builtin.template:
    src: templates/ufos.service.j2
    dest: /etc/systemd/system/ufos.service
  register: service

- name: enable ufos
  become: true
  ansible.builtin.systemd_service:
    name: ufos
    daemon_reload: "{{ service.changed }}"
    enabled: true

- name: start ufos if requested
  become: true
  ansible.builtin.systemd_service:
    name: ufos
    state: "{% if repo.changed or service.changed %}re{% endif %}started"
  when: start is defined

- name: check if snapper config is needed
  become: true
  ansible.builtin.command:
    cmd: sudo snapper list-configs --columns config
  register: snapper_existence_check

- name: set up snapper if needed
  become: true
  ansible.builtin.command:
    cmd: sudo snapper -c ufos-db create-config /mnt/data
  when: "'ufos-db' not in snapper_existence_check.stdout"

- name: copy snapper config file
  become: true
  ansible.builtin.template:
    src: templates/ufos-db-snapper.j2
    dest: /etc/snapper/configs/ufos-db

- name: copy rsync backup script
  become: true
  ansible.builtin.template:
    src: templates/nas-backup.sh.j2
    dest: /usr/local/bin/nas-backup.sh
    mode: u+rx

- name: Creates a cron file under /etc/cron.d
  become: true
  ansible.builtin.cron:
    name: backup ufos db to nas
    minute: "0"
    hour: "*/6"
    user: root
    job: /usr/local/bin/nas-backup.sh
