---
all:
  children:
    hubble:
      hosts:
        bridgy-hubble:
        hubble-hetz-01:
        hubble-pi-01:
        hubble-serv-01:
    gateway:
      hosts:
        gateway-lino-01:
    # data-only for vars until moved out of legacy
    data_only:
      hosts:
        mikrokosmos:
        orion:
        cooper:
        arietids:
