- name: install iptables-persistent
  ansible.builtin.apt:
    name: iptables-persistent

# NOTE WHEN EDITING:
# ansible will *only* modify rules that changed
# this means if you re-run this after an edit, the edited rules will be last
# so you probably wanna clear out before rerunning after any edit

- name: allow localhost
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    source: 127.0.0.1
    destination_ports: "{{ dports }}"
    jump: ACCEPT

- name: allow tailnet
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    source: 100.64.0.0/10
    destination_ports: "{{ dports }}"
    jump: ACCEPT

- name: restrict others
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_ports: "{{ dports }}"
    jump: DROP

- name: persist iptables
  ansible.builtin.command: "netfilter-persistent save"
