# head up: this role isn't great!
# we put in an nginx template, which ansible is good at...
# but then certbot modifies that file, because it's good at nginx
# so next time you run, ansible will undo certbot's work.
#
# i don't want to manually set up crons for now, so i'm doing the worse thing:
# - copying the nginx template only happens the first time.
#
# hopefully this means that ssl doesn't get undone if you rerun, *but* it will
# mean that updates to the nginx template won't be applied.

- name: install nginx
  ansible.builtin.apt:
    name: nginx

- name: add nginx config for domain
  ansible.builtin.template:
    src: templates/host.j2
    dest: /etc/nginx/sites-available/{{ hostname }}
    force: false # will not update on changes to the template!

- name: enable domain config
  ansible.builtin.file:
    src: /etc/nginx/sites-available/{{ hostname }}
    dest: /etc/nginx/sites-enabled/{{ hostname }}
    state: link

- name: check config syntax
  ansible.builtin.command: nginx -t

- name: enable and start nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: started
    enabled: true

- name: install certbot
  community.general.snap:
    name:
      - certbot
    classic: true

- name: symlink certbot
  ansible.builtin.file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link

- name: check for cert
  ansible.builtin.command: "certbot certificates -d {{ hostname }}"
  register: certbot_certs

- name: install cert
  ansible.builtin.command: "certbot run -d {{ hostname }} --nginx -n --agree-tos"
  when: "hostname not in certbot_certs.stdout"
