---
- name: Deploy hubble
  hosts: hubble
  become: true
  roles:
    - nonlocal_bind
    - role: xfs_volume
      xfs_volume_device: "{{ hubble_storage_device }}"
      xfs_volume_mount: "{{ hubble_storage_mount }}"
      when: hubble_storage_device is defined
    - node_exporter
    - hubble
    - role: nginx_tls
      nginx_tls_host: "{{ hubble_public_host }}"
      nginx_tls_extra_hosts: "{{ hubble_extra_public_hosts | default([]) }}"
      nginx_tls_upstream: "{{ hubble_bind }}"
      nginx_tls_root_redirect: "{{ hubble_root_redirect | default('') }}"
      when: hubble_public_host is defined
