---
- name: Deploy hubble
  hosts: hubble
  become: true
  roles:
    - nonlocal_bind
    - role: xfs_volume
      xfs_volume_device: "{{ hubble_storage_device }}"
      xfs_volume_mount: "{{ hubble_storage_mount }}"
      when: hubble_storage_device is defined
    - node_exporter
    - hubble
    - role: nginx
      nginx_names:
        - "{{ hubble_public_host }}"
    - hubble_proxy
    - role: nginxlog_exporter
      nginxlog_exporter_logs:
        - hubble
      nginxlog_exporter_format: "{{ nginx_log_format }}"
    - role: cert_check
      cert_check_names:
        - "{{ hubble_public_host }}"
      when: nginx_issue_certs | default(true)
