---
- hosts: all
  roles:
    # - role: hostname
    #   hostname: "{{ jetstream_hostname }}"

    - role: jetstream

    # - role: iptables_restrict
    #   dports:
    #     - 6008
    #     - 6009  # metrics

    # - role: tls_proxy
    #   hostname: "{{ jetstream_host }}"
    #   upstream: "127.0.0.1:6008"
