---
- hosts: all
  remote_user: root
  roles:
    - role: node_exporter
      node_exporter_version: "{{ node_exporter_version }}"
      node_exporter_arch: "{{ node_exporter_arch }}"

    - role: iptables_restrict
      dports:
        - 9100 # node_exporter
