---
- hosts: all
  remote_user: root
  roles:
    - role: attached_btrfs
      device: "{{ storage_device }}"
      mnt_name: "{{ mnt_name }}"

    - role: plc-ref-mirror
      acme_primary: true

    - role: iptables_restrict
      dports:
        - 6780 # plc-replica (wrapped by allegedly)
        - 9464 # metrics
