---
- hosts: all
  remote_user: root
  roles:
    - role: hostname
      hostname: "{{ relay_hostname }}"

    - role: containerized_relay
      relay_persist_dir: /home/relay/relay-persist
      relay_log_dir: /var/log/relay

    - role: iptables_restrict
      dports:
        - 2470
        - 2471  # metrics

    - role: tls_proxy
      hostname: "{{ relay_host }}"
      upstream: "127.0.0.1:2470"
