---

# prepare a raspi with raspbian lite (64bit) with an ssh key configured
# set up your hostname during imaging

# connect external storage (ssd) for the data, prefereably nvme

# use constellation-vars.example.yml to get things configured

- hosts: all
  remote_user: "{{ pi_user }}"
  roles:
    - role: hostname
      hostname: "{{ hostname }}"

    - role: spacedust
      user: "{{ pi_user }}"
      jetstream: "{{ jetstream }}"
