---
# plz change these if you are not me thx
operator_contact: "@bad-example.com"
operator_email: phil@bad-example.com

node_exporter_version: "1.9.1"
node_exporter_arch: linux-amd64 # override in host_vars for hosts on others

node_exporter_port: 9100
node_exporter_listen: "{{ tailscale_ip }}:{{ node_exporter_port }}"

nginxlog_exporter_version: "1.11.0"
nginxlog_exporter_arch: linux_amd64
nginxlog_exporter_address: "{{ tailscale_ip }}"
nginxlog_exporter_port: 4044

# shared for nginx / nginxlog_exporter (metrics)
nginx_log_format: '$remote_addr - $remote_user [$time_local] "$request" $status $upstream_cache_status $body_bytes_sent "$http_referer" "$http_user_agent" $request_time'
