---
# plz change these if you are not me thx
operator_contact: "@bad-example.com"
operator_email: phil@bad-example.com

node_exporter_version: "1.9.1"
node_exporter_arch: linux-amd64 # override in host_vars for hosts on others

# prob should firewall this off from public
node_exporter_listen: ":9100"
